### ISSUE TITLE
"App part is not configured"

### ISSUE THREAD

**Issue by RoelR** [MastekApps/FaqPage#18]
Whenever I add the webpart 'Faq client web part' to a modern site, I keep seeing the text:
 "App part is not configured.
Please, edit app part to configure its properties."
whenever I republish the site. I've dragged the source FAQ to the Web Part's Faq Sets, but it doesn't seem to save this setting, because whenever I edit the webpart again, the source is back to "Source FAQ sets".
I've added an image to explain to show what it looks like:
![Knipsel](https://user-images.githubusercontent.com/61187534/74729556-ed41fd00-5244-11ea-98dc-cdce24c29389.PNG)

I've created a source FAQ with some question, for testing purposes, but it doesn't pop up sadly. Is this a bug with modern SharePoint sites, or am I doing something wrong?

**Comment by s-KaiNet** [comment]
Hi, 
there some issues with FAQ Page on modern pages, due to some limitations enforced by modern pages in regards to "old" web parts.   
To resolve the issue, edit web part properties and change the height to be 800:  

![image](https://user-images.githubusercontent.com/10658276/74731518-2f753980-5259-11ea-89f8-5485f2c7a6d1.png)

Then at the bottom you will be able to see "Save" button.

**Comment by RoelR** [comment]
That's it! Thank you so much for your quick response.
